server:
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 30s

  port: 8083
spring:
  application:
    name: smart-interview-ai
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
