server:
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 30s

  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

spring:
  application:
    name: smart-interview-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
